# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 466df89aeadbe9f6e5c8f976f3dffff59812363ddd918ed839524102bac452eb91d154b2c8feabf426b6d50251e5839be0f00f2eef9da033a44d767ef6f87740

test:
  secret_key_base: 5039e8a429ea949411f497b8f0cb06fa0574679752f7b583dcf821be51d02f95e1f3233f3054dfe897f30ddad6859404163029cb27fa6ea2cd6fa96727a7197e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
